/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.lombok)
}

dependencies {
  api(project(":mc-annotations"))

    implementation(libs.commonsBeanUtils)
    implementation(libs.commonsConfig)
    implementation(libs.commonsIo)
    implementation(libs.commonsLang3)
    implementation(libs.jakartaAnnotations)
    implementation(libs.jmustache)
    implementation(libs.picocli)
    implementation(libs.freemarker)
    implementation(libs.guice)
    implementation(libs.guava)
    implementation(libs.jacksonYaml)
    implementation(libs.slf4jApi)

    testImplementation(platform(libs.junitBillOfMaterial))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junitSystemRules)
    testImplementation(libs.truth)
    testImplementation(libs.mockito)

//    integrationTestImplementation(platform(libs.junitBillOfMaterial))
//    integrationTestImplementation(libs.junitJupiter)
//    integrationTestImplementation(libs.junitSystemRules)
//    integrationTestImplementation(libs.truth)
//    integrationTestImplementation(libs.mockito)
}
