# This is a TOML document

title = "Default Project Structure"
version = "1.0"

# All paths are relative to basePath.
# As such, prefixing all paths with ```_BASEPATH_``` is unnecessary.
# TOML syntax does not allow keys containing the characters '$', '{' or '}'.
# Instead, the underscore ("_") is used.

[exceptions]
archetypes = ["BadRequestException", "ResourceNotFoundException", "UnprocessableEntityException"]

# This handles the base path, "/".
[api.home]
archetypes = ["RootController", "RootService"]

# This package contains infrastructure
[infra]

[infra.advice]
archetypes = "GlobalExceptionHandler"

[infra.config]
archetypes = ["ApplicationConfiguration",
    "DateTimeFormatConfiguration",
    "ProblemConfiguration",
    "LocalDateConverter",
    "WebMvcConfiguration"]

[infra.profiles]
archetypes = "SpringProfiles"

[infra.utils]
archetypes = "SecureRandomSeries"

[infra.trait]
archetypes = ["ResourceIdTrait"]

[infra.validation]
archetypes = ["AlphabeticAnnotation, ResourceIdAnnotation, AlphabeticValidator, ResourceIdValidator"]


