logging:
  level:
    root: ERROR
    org.springframework: ERROR
    mmm.coffee: WARN
  pattern:
    console: "[%p] %c{1} - %m%n"
    file: "[%p] %c{1} - %m%n"

spring:
  main:
    banner-mode: off
    
  output:
    ansi:
      enabled: detect

app:
  package-schema: packages.toml
  spring:
    dependency-file: /spring/dependencies/dependencies.yml
    templates:
      base-directory: /spring/templates
      docker: /spring/templates/docker
      lombok: /spring/templates/lombok
      gradle: /spring/templates/gradle
      spring-common: /spring/templates/common
      spring-webmvc: /spring/templates/webmvc

