/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.versions)
}

dependencies {
    implementation(libs.guice)
    implementation(libs.jakartaInject)
}
